export type Book = { title: string; author: string; note: string; category: string }
export type Film = { title: string; type: 'Anime' | 'TV Series' | 'Film'; rating: string; watchStatus: 'Sudah selesai' | 'Belum nonton' | 'Sedang nonton'; genres: string[]; progress: string; malRating: string; generalRating?: string; poster?: string; source?: string }
export type Reflection = { number: string; title: string; excerpt: string; theme: string }
export type Experience = { company: string; role: string; period: string; location: string; description: string; logo: string }
export type Volunteering = { organization: string; role: string; period: string; location: string; description: string; logo: string }
export type Honor = { title: string; issuer: string; period: string; description: string }

export const linkedinUrl = 'https://www.linkedin.com/in/samuel-simanjuntak-b9b98b2b0/'


export const experiences: Experience[] = [
  { company: 'Lembaga Alkitab Indonesia', role: 'Production Planning Control', period: 'Jul 2026 – Aug 2026', location: 'Cibinong, West Java, Indonesia · On-site', logo: '/logos/logo-lai.png', description: 'Engaged directly on the shop floor during daily operations, proactively identifying and troubleshooting bottlenecks across the production line to ensure seamless workflows. Analyzed machinery performance, specifically for Goss Community SSC Web Offset Press and Heidelberg Speedmaster Printing Machines, utilizing the Overall Equipment Effectiveness (OEE) methodology to identify bottlenecks and optimize utilization rates. Performed comprehensive Life Cycle Cost (LCC) analysis on critical production equipment to evaluate long-term cost efficiency and support strategic maintenance planning. Developed analytical reports and practical proposals aimed at improving machinery reliability and reducing operational downtime on the shop floor.' },
  { company: 'Persekutuan Mahasiswa Kristen Institut Teknologi Sumatera (PMK ITERA)', role: 'Head of Operations', period: 'Feb 2025 – Feb 2026', location: 'Lampung, Indonesia · On-site', logo: '/logos/logo-pmk-itera.png', description: 'Served as Head of Operations, leading and coordinating the Logistics and Accommodation divisions to ensure all activities ran effectively, safely, and systematically. Managed operational planning, equipment distribution and oversight, event transportation and accommodation, and the implementation of occupational health and safety standards. Coordinated across divisions, controlled budget efficiency, mitigated field risks, developed operational SOPs, ensured safety compliance, and evaluated activities after completion.' },
  { company: 'Persekutuan Mahasiswa Kristen Institut Teknologi Sumatera (PMK ITERA)', role: 'Head of Logistics Division', period: 'Feb 2024 – Feb 2025', location: 'Lampung, Indonesia · On-site', logo: '/logos/logo-pmk-itera.png', description: 'Served in the PMK Logistics Division with primary responsibility for planning, procuring, managing, and distributing operational needs and event equipment. Promoted after contributing to the Accommodation team, bringing a broad understanding of field operations. Ensured event requirements were delivered on time, cost-efficiently, and in coordination with other divisions. Prepared needs lists, sourced and negotiated with vendors, managed inventory, and supervised technical execution during events.' },
  { company: 'Persekutuan Mahasiswa Kristen Institut Teknologi Sumatera (PMK ITERA)', role: 'Accommodation Staff', period: 'Feb 2023 – Feb 2024', location: 'Lampung, Indonesia · On-site', logo: '/logos/logo-pmk-itera.png', description: 'Supported accommodation and logistics needs across organizational activities, including transportation arrangements, equipment distribution, and technical readiness in the field. Collaborated with the team to ensure operational requirements were available and delivered according to plan.' },
  { company: 'Batavia ITERA', role: 'Head of Inventory Division', period: 'Jan 2025 – Jan 2026', location: 'Lampung, Indonesia · Remote', logo: '/logos/logo-batavia-itera.png', description: 'Served as Head of Inventory, managing, overseeing, and optimizing organizational assets and equipment in a systematic and structured manner. Maintained records of incoming and outgoing items, controlled asset usage, and planned inventory maintenance to ensure operational availability and readiness. Developed a more organized and accountable inventory administration system, reduced the risk of loss or duplicate procurement, and coordinated needs planning with other divisions.' },
]

export const education = [
  { institution: 'SMA N 10 JAKARTA', program: 'Natural Sciences', period: 'Jul 2020 – May 2022', logo: '/logos/logo-sman-10-jakarta.png' },
  { institution: 'Institut Teknologi Sumatera', program: 'Bachelor of Engineering, Industrial Engineering', period: '2022 – Present', logo: '/logos/logo-itera.png' },
]

export const volunteering: Volunteering[] = [
  { organization: 'Persekutuan Mahasiswa Kristen Institut Teknologi Sumatera (PMK ITERA)', role: 'Head of Operations Division – ITERA Christmas Event', period: 'Oct 2024 – Dec 2024 · 3 mos', location: 'Lampung, Indonesia', logo: '/logos/logo-pmk-itera.png', description: 'Directed large-scale operations for the annual ITERA Christmas event, successfully managing crowd control and logistical execution for an audience of over 1,000 attendees.\n\nCollaborated strategically with PT. Pangeran Pro Indonesia (Pangeran Event Lampung) to align operational coordination, infrastructure deployment, and sponsorship fulfillment.\n\nManaged the end-to-end technical setup, including the spatial layout of a 10x8 meter main stage and the configuration of advanced sound engineering systems tailored for a large-scale venue.\n\nEstablished comprehensive Standard Operating Procedures (SOPs) for event security and medical response. Organized specialized medical training for committee members and formulated emergency contingency plans to mitigate unexpected incidents.\n\nOrchestrated complex logistics and accommodations, coordinating resource distribution, equipment procurement, and lodging to support committee operations, fundraising initiatives, and the main worship services.' },
  { organization: 'Persekutuan Mahasiswa Kristen Institut Teknologi Sumatera (PMK ITERA)', role: 'Head of Operations Division – PMK ITERA Chairman Election (Pemira)', period: 'Oct 2023 – Jan 2024 · 4 mos', location: 'Lampung, Indonesia', logo: '/logos/logo-pmk-itera.png', description: 'Directed the end-to-end operational planning and logistical execution for the PMK ITERA general election (Pemira), ensuring a transparent, fair, and organized voting process.\n\nManaged the scheduling and infrastructure preparation for all election phases, including candidate campaigns, public debates, the main voting day, and the ballot-counting process.\n\nDeveloped and enforced strict Standard Operating Procedures (SOPs) for the voting mechanism and crowd management to maintain election integrity and prevent procedural discrepancies.\n\nLed a dedicated operational team over a 4-month period, proactively identifying logistical bottlenecks and ensuring optimal resource allocation across all election events.\n\nSupervised the on-the-ground execution during the final election day, guaranteeing a smooth flow of voters and a secure environment for ballot processing.' },
]

export const skills = ['Operational Management', 'Risk & Performance Management', 'Industrial Management', 'Industrial Economics & Finance', 'Quality & Efficiency Improvement', 'Green Industry', 'Technology Valuation Management']
export const honors: Honor[] = [{ title: 'Top 10 Finalist: Investment Competition EFFECT UNS 2024', issuer: 'Himpunan Mahasiswa Program Studi Keuangan dan Perbankan, Sekolah Vokasi, Universitas Sebelas Maret', period: 'Sep 2024', description: 'Selected as a Top 10 Finalist in the EFFECT UNS 2024 Investment Competition. The competition involved a rigorous live trading phase and a comprehensive final presentation stage.\n\n• Executed active trading strategies over a consecutive two-week period using the Phillip Sekuritas Indonesia platform.\n• Secured a position in the Top 10 by achieving one of the highest cumulative portfolio returns among all participants.\n• Invited to Universitas Sebelas Maret to present and defend my trading methodologies, market analysis, and decision-making process live before a panel of judges.' }]

export const books: Book[] = []

export const films: Film[] = []

export const reflections: Reflection[] = []

export const principles = ['Curiosity over certainty', 'Depth over noise', 'Consistency over urgency']
