import { PageChrome, PageIntro } from '@/components/page-chrome'
import { education, experiences, honors, linkedinUrl, skills } from '@/lib/content'

export default function ResumePage() {
  return <PageChrome><main><PageIntro label="Resume" title={<>Experience <em>with a point of view.</em></>} description="An overview of Samuel Simanjuntak’s experience in industrial engineering, operations, production planning, and asset management." />
    <section className="section-shell page-section"><div className="resume-detail-grid"><div><p className="eyebrow">Profile</p><p className="muted-copy">Industrial Engineering student at Institut Teknologi Sumatera with a practical interest in production systems, operational coordination, maintenance, and the thoughtful management of resources.</p><a className="button button-dark resume-link" href={linkedinUrl} target="_blank" rel="noreferrer">View LinkedIn <span aria-hidden="true">↗</span></a></div><div><p className="eyebrow">Top skills</p><div className="skill-list">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div><p className="eyebrow resume-sub-label">Honors</p>{honors.map((honor) => <p className="muted-copy" key={honor}>{honor}</p>)}</div></div></section>
    <section className="section-shell page-section section-rule"><p className="eyebrow">Experience</p><div className="detail-list">{experiences.map((item) => <article className="detail-item" key={`${item.company}-${item.role}`}><div className="detail-meta"><span>{item.period}</span><span>{item.location}</span></div><div><h2>{item.role}</h2><h3>{item.company}</h3><p>{item.description}</p></div></article>)}</div></section>
    <section className="section-shell page-section section-rule"><p className="eyebrow">Education</p><div className="education-list">{education.map((item) => <article className="education-item" key={item.institution}><div><h2>{item.institution}</h2><p>{item.program}</p></div><span>{item.period}</span></article>)}</div></section>
  </main></PageChrome>
}
