import { PageChrome, PageIntro } from '@/components/page-chrome'
import { education, experiences, honors, linkedinUrl, skills, volunteering } from '@/lib/content'

export default function ResumePage() {
  return <PageChrome><main><PageIntro label="Resume" title={<>Experience <em>with a point of view.</em></>} description="An overview of Samuel Simanjuntak’s experience in industrial engineering, operations, production planning, and asset management." />
    <section className="section-shell page-section"><div className="resume-detail-grid"><div><p className="eyebrow">Profile</p><p className="muted-copy">Industrial Engineering student at Institut Teknologi Sumatera with a practical interest in production systems, operational coordination, maintenance, and the thoughtful management of resources.</p><a className="button button-dark resume-link" href={linkedinUrl} target="_blank" rel="noreferrer">View LinkedIn <span aria-hidden="true">↗</span></a></div><div><p className="eyebrow">Top skills</p><div className="skill-list">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></div></section>
    <section className="section-shell page-section section-rule"><h2 className="resume-section-title">Education</h2><div className="education-list">{education.map((item) => <article className="education-item" key={item.institution}><img className="education-logo" src={item.logo} alt="" /><div><h2>{item.institution}</h2><p>{item.program}</p></div><span>{item.period}</span></article>)}</div></section>
    <section className="section-shell page-section section-rule"><h2 className="resume-section-title">Honors &amp; awards</h2><div className="honors-list">{honors.map((honor) => <article className="honor-item" key={honor.title}><h2>{honor.title}</h2><p className="honor-meta">Issued by {honor.issuer} · {honor.period}</p><p className="preserve-lines">{honor.description}</p></article>)}</div></section>
    <section className="section-shell page-section section-rule"><h2 className="resume-section-title">Experience</h2><div className="detail-list">{experiences.map((item) => <article className="detail-item" key={`${item.company}-${item.role}`}><div className="detail-meta"><span>{item.period}</span><span>{item.location}</span></div><div className="detail-content"><img className="resume-logo" src={item.logo} alt="" /><div><h2>{item.role}</h2><div className="company-heading"><h3>{item.company}</h3></div><p>{item.description}</p></div></div></article>)}</div></section>
    <section className="section-shell page-section section-rule"><h2 className="resume-section-title">Volunteering</h2><div className="detail-list">{volunteering.map((item) => <article className="detail-item" key={item.role}><div className="detail-meta"><span>{item.period}</span><span>{item.location}</span></div><div className="detail-content"><img className="resume-logo" src={item.logo} alt="" /><div><h2>{item.role}</h2><div className="company-heading"><h3>{item.organization}</h3></div><p className="preserve-lines">{item.description}</p></div></div></article>)}</div></section>
  </main></PageChrome>
}
